version: '3.8'

services:
  app:
    build: .
    container_name: mp3_duration_app
    volumes:
      - .:/app
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    networks:
      - nginx_bridge

networks:
  nginx_bridge:
    external: true